### PR TITLE
sync the jupyterlab version to 3.0.16

### PR DESCRIPTION
**Pull request by harshad16**
sync the jupyterlab version to 3.0.16
Signed-off-by: Harshad Reddy Nalla <hnalla@redhat.com>

This is to keep the version pinned down.
This would be tested in the notebook.
We need to release the tag after we merge this.

- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [x] JIRA link(s): https://issues.redhat.com/browse/RHODS-1607
- [x] The Jira story is acked
- [x] An entry has been added to the latest build document in [Build Announcements Folder](https://drive.google.com/drive/folders/1sgkK1WZgGo9CXsLizNe0GbAzVKuSKrZL).
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious)

### CODE REVIEW

**Comment by harshad16** [comment]
we can ignore the build-check, it is not configured properly.

**Comment by tmckayus** [comment]
similar comment here as on pytorch, we need to check changes against imagestream annotations

**Comment by tmckayus** [comment]
{"name":"TensorFlow","version":"2.4.1"},{"name":"Tensorboard","version":"2.5.0"},{"name":"Boto3","version":"1.17.11"},{"name":"Kafka-Python","version":"2.0.2"},{"name":"Matplotlib","version":"3.4.1"},{"name":"Numpy","version":"1.19.2"},{"name":"Pandas","version":"1.2.4"},{"name":"Scipy","version":"1.6.2"}

**Comment by tmckayus** [comment]
hmm tensorboard says 2.6.0 in Pipfile.lock but doesn't look like it was changed by this commit, maybe the annotation was already incorrect?

everything else matches

**Comment by tmckayus** [comment]
It was changed by this commit on 9/13 by @harshad16 :)

2eef7ac898468440dc9b10c2ad34902c7bca7993

Can we pin tensorboard back to 2.5.0 so that it does not diverge from the imagestream annotations?

**Review by tmckayus — APPROVED** [review]

**Pull request merged**
